In [1]:
import pandas as pd

In [2]:
csv = 'data.csv'
data = pd.read_csv(csv)
df = pd.DataFrame(data)
print(df)

      id           nama        warna bentuk kristal
0      4  healthy.0.jpg   coklat tua  padat      ya
1      5    cocci.1.jpg  coklat muda   cair   tidak
2      6    cocci.3.jpg  coklat muda   cair   tidak
3      7    cocci.2.jpg  coklat muda   cair   tidak
4      8    cocci.0.jpg  coklat muda   cair   tidak
..   ...            ...          ...    ...     ...
97   101    ncd.156.jpg   hijau muda   cair   tidak
98   102     ncd.86.jpg   hijau muda   cair   tidak
99   103     ncd.93.jpg   hijau muda   cair   tidak
100  104     ncd.86.jpg   hijau muda   cair   tidak
101  105    ncd.161.jpg   hijau muda   cair   tidak

[102 rows x 5 columns]


In [3]:
duplikat_nama = df[df.duplicated(['nama'])]
print('Duplikat berdasarkan nama:')
print(duplikat_nama)

Duplikat berdasarkan nama:
      id        nama       warna bentuk kristal
94    98  ncd.68.jpg  hijau muda   cair   tidak
100  104  ncd.86.jpg  hijau muda   cair   tidak


In [4]:
df = df.assign(kesehatan=df['nama'].str.split(".").str.get(0))
df

id           nama        warna bentuk kristal kesehatan
0      4  healthy.0.jpg   coklat tua  padat      ya   healthy
1      5    cocci.1.jpg  coklat muda   cair   tidak     cocci
2      6    cocci.3.jpg  coklat muda   cair   tidak     cocci
3      7    cocci.2.jpg  coklat muda   cair   tidak     cocci
4      8    cocci.0.jpg  coklat muda   cair   tidak     cocci
..   ...            ...          ...    ...     ...       ...
97   101    ncd.156.jpg   hijau muda   cair   tidak       ncd
98   102     ncd.86.jpg   hijau muda   cair   tidak       ncd
99   103     ncd.93.jpg   hijau muda   cair   tidak       ncd
100  104     ncd.86.jpg   hijau muda   cair   tidak       ncd
101  105    ncd.161.jpg   hijau muda   cair   tidak       ncd

[102 rows x 6 columns]

In [5]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [6]:
df['warna_encode'] = label_encoder.fit_transform(df['warna'])
df['bentuk_encode'] = label_encoder.fit_transform(df['bentuk'])
df['kristal_encode'] = label_encoder.fit_transform(df['kristal'])
df['kesehatan_encode'] = label_encoder.fit_transform(df['kesehatan'])
df

id           nama        warna bentuk kristal kesehatan  warna_encode  \
0      4  healthy.0.jpg   coklat tua  padat      ya   healthy             1   
1      5    cocci.1.jpg  coklat muda   cair   tidak     cocci             0   
2      6    cocci.3.jpg  coklat muda   cair   tidak     cocci             0   
3      7    cocci.2.jpg  coklat muda   cair   tidak     cocci             0   
4      8    cocci.0.jpg  coklat muda   cair   tidak     cocci             0   
..   ...            ...          ...    ...     ...       ...           ...   
97   101    ncd.156.jpg   hijau muda   cair   tidak       ncd             2   
98   102     ncd.86.jpg   hijau muda   cair   tidak       ncd             2   
99   103     ncd.93.jpg   hijau muda   cair   tidak       ncd             2   
100  104     ncd.86.jpg   hijau muda   cair   tidak       ncd             2   
101  105    ncd.161.jpg   hijau muda   cair   tidak       ncd             2   

     bentuk_encode  kristal_encode  kesehatan_encode  
0                1               1                 1  
1                0               0                 0  
2                0               0                 0  
3                0               0                 0  
4                0               0                 0  
..             ...             ...               ...  
97               0               0                 2  
98               0               0                 2  
99               0               0                 2  
100              0               0                 2  
101              0               0                 2  

[102 rows x 10 columns]

Note:
Warna:
0:Coklat muda
1:Coklat tua
2:Hijau muda
3:Hitam

Bentuk:
0:cair
1:padat

Kristal:
0:tidak
1:ya

Kesehatan:
0: cocci
1: healthy
2: ncd
3: salmo

In [7]:
df = df.drop(['id','warna','bentuk','kristal','kesehatan'], axis=1)
df

nama  warna_encode  bentuk_encode  kristal_encode  \
0    healthy.0.jpg             1              1               1   
1      cocci.1.jpg             0              0               0   
2      cocci.3.jpg             0              0               0   
3      cocci.2.jpg             0              0               0   
4      cocci.0.jpg             0              0               0   
..             ...           ...            ...             ...   
97     ncd.156.jpg             2              0               0   
98      ncd.86.jpg             2              0               0   
99      ncd.93.jpg             2              0               0   
100     ncd.86.jpg             2              0               0   
101    ncd.161.jpg             2              0               0   

     kesehatan_encode  
0                   1  
1                   0  
2                   0  
3                   0  
4                   0  
..                ...  
97                  2  
98                  2  
99                  2  
100                 2  
101                 2  

[102 rows x 5 columns]

In [8]:
X = df.iloc[:, [1, 2, 3]].values
X

array([[1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 0],
       [1, 1, 1],
       [2, 1, 1],
       [1, 1, 1],
       [2, 1, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [3, 1, 1],
       [3, 1, 1],
       [3, 1, 1],
       [3, 1, 1],
       [3, 1, 1],
       [3,

In [9]:
y = df.iloc[:, -1].values
y

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)

In [11]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

In [12]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 10, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [13]:
y_pred = classifier.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score,f1_score, recall_score

cm = confusion_matrix(y_test, y_pred)
recall= recall_score(y_test,y_pred,pos_label='positive',average='micro')
f1= f1_score(y_test,y_pred,pos_label='positive',average='micro')
ac = accuracy_score(y_test,y_pred)
print("Confussion Matrix: ",cm)
print("recall: ",recall)
print("f1: ",f1)
print("Accuration: ",ac)

Confussion Matrix:  [[9 0 0 0]
 [0 6 0 0]
 [0 0 8 0]
 [0 2 0 6]]
recall:  0.9354838709677419
f1:  0.9354838709677419
Accuration:  0.9354838709677419


C:\Users\acer\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\acer\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [19]:
import numpy as np
X_new = np.array([[1, 1, 1],
       [0, 0, 0],[3, 1, 1],
       [2, 0, 0]])
# X_new = sc.fit_transform(X_new)
# Lakukan prediksi menggunakan model KNN
y_pred = classifier.predict(X_new)

# Tampilkan hasil prediksi
print("Hasil prediksi: ", y_pred)

Hasil prediksi:  [1 0 3 2]


In [20]:
from joblib import dump

In [21]:
dump(classifier, 'knn_model.joblib')

['knn_model.joblib']

In [23]:
import pickle

# Simpan model KNN ke dalam file 'knn_model.pkl'
with open('knn_model.pkl', 'wb') as f:
    pickle.dump(classifier, f)